Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -15,20 +15,12 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v6
-      - name: Install BunJS
-        uses: oven-sh/setup-bun@v2
-      - name: Install dependencies
-        run: bun i
-      - name: Build
-        env:
-          BASE_PATH: ""
-        run: bun run build
-      - name: Upload Artifacts
-        uses: actions/upload-pages-artifact@v4
-        with:
-          # this should match the `pages` option in your adapter-static options
-          path: "build/"
-
+      - name: Update apt and Install Comrak
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y comrak
+      - name: Check
+        run: comrak --version || echo "Not found"
   deploy:
     needs: build
     runs-on: ubuntu-latest
